import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Loader2, ShieldCheck, Sparkles, UserRound } from "lucide-react";
import { useLanguage } from "@/contexts/LanguageContext";

export default function AdminContributors() {
  const { user, isAuthenticated, startLogin } = useAuth();
  const { t } = useLanguage();
  const utils = trpc.useUtils();
  const allowed = isAuthenticated && (user?.role === "admin" || user?.role === "moderator");
  const candidates = trpc.moderation.getIntakeCandidates.useQuery({ limit: 50 }, { enabled: allowed });
  const applications = trpc.moderation.getVerificationApplications.useQuery({ status: "pending" }, { enabled: allowed });
  const reviewCandidate = trpc.moderation.reviewIntakeCandidate.useMutation({ onSuccess: async () => { await utils.moderation.getIntakeCandidates.invalidate(); } });
  const reviewVerification = trpc.moderation.reviewVerificationApplication.useMutation({ onSuccess: async () => { await utils.moderation.getVerificationApplications.invalidate(); } });

  if (!isAuthenticated) return <div className="container py-16 text-center"><Card className="mx-auto max-w-lg p-8"><h1 className="text-2xl font-bold">{t("signInRequired")}</h1><Button className="mt-5" onClick={() => startLogin()}>{t("signIn")}</Button></Card></div>;
  if (!allowed) return <div className="container py-16 text-center"><Card className="mx-auto max-w-lg p-8"><h1 className="text-2xl font-bold">{t("qualityAccessDenied")}</h1></Card></div>;

  return <div className="ns-noise min-h-screen py-10"><div className="container max-w-6xl"><div className="rounded-3xl border border-violet-100 bg-[radial-gradient(circle_at_90%_10%,rgba(221,214,254,.75),transparent_30%),white] p-7 shadow-sm"><div className="inline-flex items-center gap-2 text-sm font-bold uppercase tracking-[.14em] text-violet-700"><ShieldCheck className="h-4 w-4" />{t("humanOversight")}</div><h1 className="mt-3 font-['Sora'] text-3xl font-bold tracking-tight text-slate-950">Contributor intake & verification</h1><p className="mt-2 max-w-2xl text-slate-600">Review contributor-provided candidates and manual verification requests. Faster-lane eligibility never bypasses a human decision.</p></div>
    <div className="mt-6 grid gap-6 lg:grid-cols-2"><Card className="ns-surface border-slate-200 p-5"><div className="flex items-center gap-2"><Sparkles className="h-5 w-5 text-sky-600" /><div><h2 className="font-['Sora'] text-xl font-bold">Intake candidates</h2><p className="text-sm text-slate-500">Private drafts explicitly submitted by contributors.</p></div></div>{candidates.isLoading ? <Loader2 className="mx-auto my-10 h-5 w-5 animate-spin" /> : candidates.data?.length ? <div className="mt-5 space-y-3">{candidates.data.map((candidate) => <div key={candidate.id} className="rounded-2xl border border-slate-200 bg-white p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="font-semibold text-slate-900">{candidate.title || candidate.url || "Untitled candidate"}</p><p className="mt-1 truncate text-sm text-slate-500">{candidate.url}</p></div>{candidate.contributorVerified === "approved" && <Badge className="bg-emerald-100 text-emerald-700 hover:bg-emerald-100">{t("verifiedContributor")}</Badge>}</div><p className="mt-3 text-xs text-slate-500">{candidate.contributorName || "Contributor"} · {candidate.candidateType}</p><div className="mt-4 flex flex-wrap gap-2"><Button size="sm" className="bg-emerald-600 text-white hover:bg-emerald-700" disabled={reviewCandidate.isPending} onClick={() => reviewCandidate.mutate({ candidateId: candidate.id, status: "accepted" })}>{t("approve")}</Button><Button size="sm" variant="outline" disabled={reviewCandidate.isPending} onClick={() => reviewCandidate.mutate({ candidateId: candidate.id, status: "duplicate" })}>Duplicate</Button><Button size="sm" variant="outline" className="text-rose-700" disabled={reviewCandidate.isPending} onClick={() => reviewCandidate.mutate({ candidateId: candidate.id, status: "rejected" })}>{t("reject")}</Button></div></div>)}</div> : <p className="py-10 text-center text-sm text-slate-500">No submitted intake candidates are waiting for review.</p>}</Card>
    <Card className="ns-surface border-slate-200 p-5"><div className="flex items-center gap-2"><UserRound className="h-5 w-5 text-violet-600" /><div><h2 className="font-['Sora'] text-xl font-bold">{t("verification")}</h2><p className="text-sm text-slate-500">Manual portfolio and accepted-work review.</p></div></div>{applications.isLoading ? <Loader2 className="mx-auto my-10 h-5 w-5 animate-spin" /> : applications.data?.length ? <div className="mt-5 space-y-3">{applications.data.map((row) => <div key={row.application.id} className="rounded-2xl border border-slate-200 bg-white p-4"><p className="font-semibold text-slate-900">{row.contributorName || row.contributorEmail || "Contributor"}</p>{row.application.portfolioUrl && <a className="mt-1 block truncate text-sm text-sky-700 hover:underline" href={row.application.portfolioUrl} target="_blank" rel="noreferrer">{row.application.portfolioUrl}</a>}<p className="mt-3 text-sm leading-6 text-slate-600">{row.application.rationale}</p><div className="mt-4 flex gap-2"><Button size="sm" className="bg-emerald-600 text-white hover:bg-emerald-700" disabled={reviewVerification.isPending} onClick={() => reviewVerification.mutate({ applicationId: row.application.id, status: "approved" })}>{t("approve")}</Button><Button size="sm" variant="outline" className="text-rose-700" disabled={reviewVerification.isPending} onClick={() => reviewVerification.mutate({ applicationId: row.application.id, status: "rejected" })}>{t("reject")}</Button></div></div>)}</div> : <p className="py-10 text-center text-sm text-slate-500">No verification applications are waiting for review.</p>}</Card></div>
  </div></div>;
}
