import { useState } from "react";
import { useLocation } from "wouter";
import { CheckCircle2, ClipboardCheck, FilePlus2, ShieldAlert, XCircle } from "lucide-react";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";

export default function AdminIngestion() {
  const { user, isAuthenticated } = useAuth();
  const [, navigate] = useLocation();
  const [name, setName] = useState("");
  const [baseUrl, setBaseUrl] = useState("");
  const [termsUrl, setTermsUrl] = useState("");
  const [sourceType, setSourceType] = useState<"official_site" | "official_docs" | "official_repository" | "manual_feed">("official_site");
  const isAdmin = isAuthenticated && user?.role === "admin";
  const { data: sources, refetch: refetchSources } = trpc.moderation.getIngestionSources.useQuery({}, { enabled: isAdmin });
  const { data: candidates, refetch: refetchCandidates } = trpc.moderation.getIngestionCandidates.useQuery({ limit: 50 }, { enabled: isAdmin });
  const createSource = trpc.moderation.createIngestionSource.useMutation({ onSuccess: () => { toast.success("Named source registered for review"); setName(""); setBaseUrl(""); setTermsUrl(""); refetchSources(); }, onError: (error) => toast.error(error.message) });
  const reviewSource = trpc.moderation.reviewIngestionSource.useMutation({ onSuccess: () => { toast.success("Source decision recorded"); refetchSources(); }, onError: (error) => toast.error(error.message) });
  const reviewCandidate = trpc.moderation.reviewIngestionCandidate.useMutation({ onSuccess: () => { toast.success("Candidate decision recorded"); refetchCandidates(); }, onError: (error) => toast.error(error.message) });

  if (!isAdmin) return <div className="container py-16"><Card className="ns-surface mx-auto max-w-xl p-8 text-center"><ShieldAlert className="mx-auto h-10 w-10 text-amber-500" /><h1 className="mt-4 text-2xl font-semibold text-[var(--ns-ink)]">Administrator access required</h1><p className="mt-3 text-sm text-[var(--ns-muted)]">Source ingestion is review-only and available only to administrators.</p><Button className="mt-6" onClick={() => navigate("/")}>Go to Home</Button></Card></div>;

  return <div className="ns-noise min-h-screen py-10"><div className="container max-w-6xl"><header className="ns-surface rounded-3xl p-7 shadow-sm"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-sky-700">Human-reviewed external ingestion</p><h1 className="mt-2 text-3xl font-semibold text-[var(--ns-ink)]">Named-source intake</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[var(--ns-muted)]">Register only sources with clear provenance and terms. This workspace stores review candidates; it never fetches freely, creates a public resource, or publishes a relationship automatically.</p></header>
    <div className="mt-7 grid gap-6 lg:grid-cols-[0.9fr_1.1fr]"><Card className="ns-surface p-6 shadow-sm"><div className="flex items-center gap-2"><FilePlus2 className="h-5 w-5 text-sky-600" /><h2 className="font-semibold text-[var(--ns-ink)]">Register a named source</h2></div><form className="mt-5 grid gap-3" onSubmit={(event) => { event.preventDefault(); createSource.mutate({ name: name.trim(), baseUrl: baseUrl.trim(), termsUrl: termsUrl.trim() || undefined, sourceType }); }}><Input value={name} onChange={(event) => setName(event.target.value)} placeholder="Source name" required /><Input value={baseUrl} onChange={(event) => setBaseUrl(event.target.value)} placeholder="https://source.example" type="url" required /><Input value={termsUrl} onChange={(event) => setTermsUrl(event.target.value)} placeholder="Terms or license URL (optional)" type="url" /><select value={sourceType} onChange={(event) => setSourceType(event.target.value as typeof sourceType)} className="h-10 rounded-md border border-[var(--ns-border-strong)] bg-[var(--ns-elevated)] px-3 text-sm text-[var(--ns-ink)]"><option value="official_site">Official site</option><option value="official_docs">Official documentation</option><option value="official_repository">Official repository</option><option value="manual_feed">Manual reviewed feed</option></select><Button className="ns-primary-button" type="submit" disabled={createSource.isPending}>{createSource.isPending ? "Registering…" : "Register source"}</Button></form></Card>
      <div className="space-y-4"><Card className="ns-surface p-6 shadow-sm"><h2 className="font-semibold text-[var(--ns-ink)]">Source decisions</h2><div className="mt-4 space-y-3">{sources?.length ? sources.map(({ source }) => <div key={source.id} className="rounded-2xl border border-[var(--ns-line)] bg-[var(--ns-elevated)] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold text-[var(--ns-ink)]">{source.name}</p><a className="mt-1 block break-all text-sm text-sky-700" href={source.baseUrl} target="_blank" rel="noreferrer">{source.baseUrl}</a><p className="mt-2 text-xs text-[var(--ns-muted)]">{source.sourceType.replaceAll("_", " ")} · {source.status}</p></div>{source.status === "draft" && <div className="flex gap-2"><Button size="sm" onClick={() => reviewSource.mutate({ sourceId: source.id, status: "approved" })}><CheckCircle2 className="mr-1 h-3.5 w-3.5" />Approve</Button><Button size="sm" variant="outline" onClick={() => reviewSource.mutate({ sourceId: source.id, status: "retired" })}><XCircle className="mr-1 h-3.5 w-3.5" />Retire</Button></div>}</div></div>) : <p className="text-sm text-[var(--ns-muted)]">No named sources registered yet.</p>}</div></Card>
      <Card className="ns-surface p-6 shadow-sm"><div className="flex items-center gap-2"><ClipboardCheck className="h-5 w-5 text-violet-600" /><h2 className="font-semibold text-[var(--ns-ink)]">Candidate review queue</h2></div><div className="mt-4 space-y-3">{candidates?.length ? candidates.map(({ candidate, source }) => <div key={candidate.id} className="rounded-2xl border border-[var(--ns-line)] bg-[var(--ns-elevated)] p-4"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-violet-700">{source.name}</p><a className="mt-1 block break-all font-medium text-sky-700" href={candidate.externalUrl} target="_blank" rel="noreferrer">{candidate.title || candidate.externalUrl}</a><p className="mt-2 text-sm text-[var(--ns-muted)]">{candidate.summary || "No candidate summary supplied."}</p><div className="mt-3 flex gap-2"><Button size="sm" onClick={() => reviewCandidate.mutate({ candidateId: candidate.id, status: "accepted" })}>Accept for manual drafting</Button><Button size="sm" variant="outline" onClick={() => reviewCandidate.mutate({ candidateId: candidate.id, status: "rejected" })}>Reject</Button></div></div>) : <p className="text-sm text-[var(--ns-muted)]">No candidates are awaiting review.</p>}</div></Card></div></div></div></div>;
}
