import { useEffect, useMemo, useState } from "react";
import { Link, useLocation } from "wouter";
import { ArrowRight, ArrowUpRight, GitBranch, Lightbulb, Network, Search as SearchIcon, SlidersHorizontal, Sparkles, TrendingUp, X } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { applyClientSeo } from "@/lib/seo";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Skeleton } from "@/components/ui/skeleton";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

const prompts = ["Jira alternatives", "Slack integrations", "GitHub competitors", "Figma similar tools", "Notion alternatives"];
const pricingOptions = ["free", "freemium", "paid", "open_source", "enterprise"] as const;

export default function Search() {
  const [, setLocation] = useLocation();
  const initialQuery = new URLSearchParams(window.location.search).get("q") || "";
  const [query, setQuery] = useState(initialQuery);
  const [debouncedQuery, setDebouncedQuery] = useState(initialQuery);
  const [activeTab, setActiveTab] = useState<"results" | "suggestions">("results");
  const [filtersOpen, setFiltersOpen] = useState(false);
  const [categoryId, setCategoryId] = useState<number | undefined>();
  const [pricing, setPricing] = useState<(typeof pricingOptions)[number] | undefined>();
  const [tag, setTag] = useState("");

  useEffect(() => {
    applyClientSeo({ title: "Relationship-aware resource search — NorthStar", description: "Search digital resources by name, category, tags, and relationships such as alternatives or integrations.", canonicalPath: "/search" });
  }, []);
  useEffect(() => {
    const timer = window.setTimeout(() => setDebouncedQuery(query), 300);
    return () => window.clearTimeout(timer);
  }, [query]);

  const { data: categories = [] } = trpc.categories.list.useQuery();
  const filters = useMemo(() => ({ ...(categoryId ? { categoryId } : {}), ...(pricing ? { pricing } : {}), ...(tag.trim() ? { tag: tag.trim() } : {}) }), [categoryId, pricing, tag]);
  const hasFilters = Object.keys(filters).length > 0;
  const { data: results, isLoading: resultsLoading } = trpc.search.advancedSearch.useQuery({ query: debouncedQuery, limit: 50, ...(hasFilters ? { filters } : {}) }, { enabled: debouncedQuery.length > 0 });
  const { data: suggestions, isLoading: suggestionsLoading } = trpc.search.getSuggestions.useQuery({ query: debouncedQuery, limit: 5 }, { enabled: debouncedQuery.length > 2 });
  const { data: trending = [] } = trpc.search.getTrending.useQuery({ limit: 5 });

  const selectQuery = (value: string) => { setQuery(value); setDebouncedQuery(value); setActiveTab("results"); };
  const submitSearch = (event: React.FormEvent) => { event.preventDefault(); if (query.trim()) setLocation(`/search?q=${encodeURIComponent(query.trim())}`); };
  const clearFilters = () => { setCategoryId(undefined); setPricing(undefined); setTag(""); };

  return <div className="min-h-screen bg-slate-50">
    <section className="relative overflow-hidden border-b border-slate-200 bg-white"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_72%_-20%,rgba(125,211,252,0.45),transparent_35%),radial-gradient(circle_at_24%_120%,rgba(221,214,254,0.4),transparent_42%)]" /><div className="container relative py-12 md:py-16"><div className="mx-auto max-w-3xl text-center"><span className="inline-flex items-center gap-2 rounded-full border border-sky-200 bg-white/90 px-3 py-1.5 text-xs font-semibold text-sky-800"><GitBranch className="h-3.5 w-3.5" />Relationship-aware discovery</span><h1 className="mt-5 text-4xl font-bold tracking-[-0.04em] text-slate-950 md:text-5xl">Find the connection that matters.</h1><p className="mx-auto mt-4 max-w-2xl text-base leading-7 text-slate-600 md:text-lg">Search by tool, need, or relationship. NorthStar interprets the context around alternatives, integrations, competitors, and similar resources.</p><form onSubmit={submitSearch} className="mt-7"><div className="flex rounded-2xl border border-slate-200 bg-white p-2 shadow-[0_14px_34px_rgba(15,23,42,0.1)] focus-within:border-sky-300"><SearchIcon className="ml-2 mr-3 mt-3 h-5 w-5 shrink-0 text-sky-600" /><Input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Try “Jira alternatives” or “Slack integrations”" className="h-11 border-0 bg-transparent px-0 text-base shadow-none focus-visible:ring-0" autoFocus /><Button type="submit" className="h-11 rounded-xl bg-slate-900 text-white hover:bg-slate-800">Search <ArrowRight className="ml-2 h-4 w-4" /></Button></div></form><div className="mt-4 flex flex-wrap justify-center gap-2">{["Alternatives", "Integrations", "Competitors", "Similar tools"].map((item) => <button type="button" key={item} onClick={() => setQuery(item.toLowerCase())} className="rounded-full border border-slate-200 bg-white/90 px-3 py-1.5 text-xs font-semibold text-slate-600 hover:border-sky-200 hover:text-sky-700">{item}</button>)}</div></div></div></section>
    <main className="container py-10 md:py-14">{!debouncedQuery ? <EmptyState trending={trending} onSelect={selectQuery} /> : <Tabs value={activeTab} onValueChange={(value) => setActiveTab(value as "results" | "suggestions")} className="mx-auto max-w-5xl"><div className="mb-4 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold uppercase tracking-[0.16em] text-sky-700">Search results</p><h2 className="mt-1 text-2xl font-semibold tracking-tight text-slate-950">Results for “{debouncedQuery}”</h2></div><div className="flex flex-wrap gap-2"><Button type="button" variant="outline" onClick={() => setFiltersOpen((value) => !value)} className="border-slate-300 bg-white text-slate-700"><SlidersHorizontal className="mr-2 h-4 w-4" />{hasFilters ? "Filters active" : "Filters"}</Button><TabsList className="h-auto rounded-xl border border-slate-200 bg-white p-1 shadow-sm"><TabsTrigger value="results" className="rounded-lg px-3 py-2 text-sm">Results{results ? ` (${results.length})` : ""}</TabsTrigger><TabsTrigger value="suggestions" className="rounded-lg px-3 py-2 text-sm">Suggestions</TabsTrigger></TabsList></div></div>{filtersOpen && <FilterPanel categories={categories} categoryId={categoryId} pricing={pricing} tag={tag} onCategory={setCategoryId} onPricing={setPricing} onTag={setTag} onClear={clearFilters} />}<TabsContent value="results" className="mt-0"><Results query={debouncedQuery} results={results ?? []} loading={resultsLoading} /></TabsContent><TabsContent value="suggestions" className="mt-0"><Suggestions data={suggestions} loading={suggestionsLoading} onSelect={selectQuery} /></TabsContent></Tabs>}</main>
  </div>;
}

function FilterPanel({ categories, categoryId, pricing, tag, onCategory, onPricing, onTag, onClear }: { categories: any[]; categoryId?: number; pricing?: (typeof pricingOptions)[number]; tag: string; onCategory: (value?: number) => void; onPricing: (value?: (typeof pricingOptions)[number]) => void; onTag: (value: string) => void; onClear: () => void }) {
  return <Card className="mx-auto mb-5 max-w-5xl rounded-2xl border-slate-200 bg-white p-4 shadow-sm"><div className="grid gap-3 md:grid-cols-[1fr_1fr_1fr_auto]"><label className="text-xs font-semibold uppercase tracking-[0.12em] text-slate-500">Category<select value={categoryId ?? ""} onChange={(event) => onCategory(event.target.value ? Number(event.target.value) : undefined)} className="mt-1.5 block h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm font-medium normal-case tracking-normal text-slate-700"><option value="">All categories</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label className="text-xs font-semibold uppercase tracking-[0.12em] text-slate-500">Pricing<select value={pricing ?? ""} onChange={(event) => onPricing(event.target.value ? event.target.value as (typeof pricingOptions)[number] : undefined)} className="mt-1.5 block h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm font-medium normal-case tracking-normal text-slate-700"><option value="">All pricing</option>{pricingOptions.map((item) => <option key={item} value={item}>{item.replace("_", " ")}</option>)}</select></label><label className="text-xs font-semibold uppercase tracking-[0.12em] text-slate-500">Tag<Input value={tag} onChange={(event) => onTag(event.target.value)} placeholder="e.g. collaboration" className="mt-1.5 h-10 border-slate-200 text-sm font-medium normal-case tracking-normal" /></label><div className="flex items-end"><Button type="button" variant="ghost" onClick={onClear} className="h-10 text-slate-600"><X className="mr-1 h-4 w-4" />Clear</Button></div></div></Card>;
}

function EmptyState({ trending, onSelect }: { trending: string[]; onSelect: (value: string) => void }) { return <div className="mx-auto grid max-w-5xl gap-5 lg:grid-cols-[0.92fr_1.08fr]"><Card className="rounded-2xl border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-sky-50 text-sky-700"><TrendingUp className="h-5 w-5" /></span><div><p className="text-sm font-semibold text-slate-950">Trending in the graph</p><p className="text-xs text-slate-500">Start with a live resource signal.</p></div></div><div className="mt-5 grid gap-2">{trending.length ? trending.map((term) => <button type="button" key={term} onClick={() => onSelect(term)} className="group flex items-center justify-between rounded-xl border border-slate-200 px-3 py-3 text-left text-sm font-semibold text-slate-700 hover:border-sky-200 hover:bg-sky-50"><span>{term}</span><ArrowUpRight className="h-4 w-4 text-slate-400 group-hover:text-sky-700" /></button>) : <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">Live trend signals will appear here as the graph grows.</p>}</div></Card><Card className="rounded-2xl border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-violet-50 text-violet-700"><Lightbulb className="h-5 w-5" /></span><div><p className="text-sm font-semibold text-slate-950">Explore a relationship</p><p className="text-xs text-slate-500">Use plain language; NorthStar recognizes common graph intents.</p></div></div><div className="mt-5 grid gap-2 sm:grid-cols-2">{prompts.map((prompt) => <button type="button" key={prompt} onClick={() => onSelect(prompt)} className="rounded-xl border border-slate-200 p-4 text-left hover:border-violet-200 hover:bg-violet-50"><Network className="h-4 w-4 text-violet-600" /><p className="mt-3 text-sm font-semibold text-slate-800">{prompt}</p><p className="mt-1 text-xs text-slate-500">Open graph query <ArrowRight className="inline h-3 w-3" /></p></button>)}</div></Card></div>; }

function Results({ query, results, loading }: { query: string; results: any[]; loading: boolean }) { if (loading) return <div className="grid gap-4">{Array.from({ length: 5 }).map((_, index) => <Skeleton key={index} className="h-36 rounded-2xl" />)}</div>; if (!results.length) return <Card className="rounded-2xl border-dashed border-slate-300 bg-white p-10 text-center"><SearchIcon className="mx-auto h-9 w-9 text-slate-300" /><h3 className="mt-4 text-lg font-semibold text-slate-900">No resources matched “{query}”</h3><p className="mt-2 text-sm text-slate-500">Try a broader term, clear a filter, or browse the directory.</p><Link href="/browse"><Button variant="outline" className="mt-5">Browse resources <ArrowRight className="ml-2 h-4 w-4" /></Button></Link></Card>; return <div className="grid gap-4">{results.map((resource) => <Link key={resource.id} href={`/resource/${resource.slug}`} className="group block rounded-2xl focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sky-500"><Card className="border-slate-200 bg-white p-5 shadow-sm transition group-hover:-translate-y-0.5 group-hover:border-sky-200 group-hover:shadow-lg"><div className="flex gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center overflow-hidden rounded-xl bg-gradient-to-br from-sky-50 to-violet-50 text-sm font-bold text-sky-700">{resource.logo ? <img src={resource.logo} alt="" className="h-full w-full object-cover" /> : resource.title.slice(0, 2).toUpperCase()}</div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><div><p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-sky-700">Resource node</p><h3 className="mt-1 text-lg font-semibold text-slate-950 group-hover:text-sky-700">{resource.title}</h3></div><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold capitalize text-slate-600">{resource.pricing?.replace("_", " ")}</span></div><p className="mt-2 line-clamp-2 text-sm leading-6 text-slate-600">{resource.description || "Explore this resource and its verified graph connections."}</p><div className="mt-4 flex items-center justify-between border-t border-slate-100 pt-3 text-xs"><span className="text-slate-500">Knowledge graph node</span><span className="inline-flex items-center gap-1 font-semibold text-sky-700">Open node <ArrowRight className="h-3.5 w-3.5" /></span></div></div></div></Card></Link>)}</div>; }

function Suggestions({ data, loading, onSelect }: { data: any; loading: boolean; onSelect: (value: string) => void }) { if (loading) return <div className="grid gap-4">{Array.from({ length: 3 }).map((_, index) => <Skeleton key={index} className="h-20 rounded-xl" />)}</div>; const resources = data?.resources ?? []; const queries = data?.suggestions ?? []; if (!resources.length && !queries.length) return <Card className="rounded-2xl border-dashed border-slate-300 bg-white p-10 text-center"><Sparkles className="mx-auto h-8 w-8 text-slate-300" /><p className="mt-4 text-sm text-slate-500">Keep typing to surface resource and relationship suggestions.</p></Card>; return <div className="grid gap-5 md:grid-cols-2"><Card className="rounded-2xl border-slate-200 bg-white p-5"><h3 className="text-sm font-semibold text-slate-950">Resource suggestions</h3><div className="mt-3 space-y-2">{resources.map((resource: any) => <Link key={resource.id} href={`/resource/${resource.slug}`} className="flex items-center justify-between rounded-xl border border-slate-200 px-3 py-3 text-sm font-semibold text-slate-700 hover:border-sky-200 hover:bg-sky-50"><span className="truncate">{resource.title}</span><ArrowUpRight className="ml-3 h-4 w-4" /></Link>)}</div></Card><Card className="rounded-2xl border-slate-200 bg-white p-5"><h3 className="text-sm font-semibold text-slate-950">Related queries</h3><div className="mt-3 space-y-2">{queries.map((item: string) => <button type="button" key={item} onClick={() => onSelect(item)} className="flex w-full items-center justify-between rounded-xl border border-slate-200 px-3 py-3 text-left text-sm font-semibold text-slate-700 hover:border-violet-200 hover:bg-violet-50"><span>{item}</span><ArrowRight className="h-4 w-4" /></button>)}</div></Card></div>; }
