import { Link } from "wouter";
import { Languages, Moon, Sun, UserRound } from "lucide-react";
import { useAuth } from "@/_core/hooks/useAuth";
import { useLanguage } from "@/contexts/LanguageContext";
import { useTheme } from "@/contexts/ThemeContext";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";

export default function Settings() {
  const { isAuthenticated, startLogin } = useAuth();
  const { locale, setLocale, t } = useLanguage();
  const { theme, toggleTheme } = useTheme();
  if (!isAuthenticated) return <div className="container max-w-2xl py-16"><Card className="ns-surface p-8 text-center shadow-sm"><h1 className="text-2xl font-semibold text-slate-950">{t("settings")}</h1><p className="mt-3 text-slate-600">{t("signInToCreateCollection")}</p><Button onClick={startLogin} className="mt-6 bg-sky-600 text-white hover:bg-sky-700">{t("signIn")}</Button></Card></div>;
  return <div className="ns-noise min-h-screen py-10 md:py-14"><div className="container max-w-3xl"><header><p className="text-sm font-semibold uppercase tracking-[0.16em] text-sky-700">NorthStar</p><h1 className="mt-2 text-3xl font-semibold text-slate-950">{t("settings")}</h1><p className="mt-3 text-slate-600">{t("settingsIntro")}</p></header><div className="mt-8 grid gap-5"><Card className="ns-surface p-6 shadow-sm"><div className="flex items-start gap-4"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-sky-50 text-sky-700">{theme === "light" ? <Sun className="h-5 w-5" /> : <Moon className="h-5 w-5" />}</div><div className="min-w-0 flex-1"><h2 className="text-xl font-semibold text-slate-950">{t("appearance")}</h2><p className="mt-1 text-sm text-slate-600">{theme === "light" ? t("lightTheme") : t("darkTheme")}</p><Button onClick={toggleTheme} variant="outline" className="mt-4">{theme === "light" ? t("switchToDark") : t("switchToLight")}</Button></div></div></Card><Card className="ns-surface p-6 shadow-sm"><div className="flex items-start gap-4"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-violet-50 text-violet-700"><Languages className="h-5 w-5" /></div><div className="min-w-0 flex-1"><h2 className="text-xl font-semibold text-slate-950">{t("language")}</h2><p className="mt-1 text-sm text-slate-600">{locale === "en" ? "English" : "العربية"}</p><div className="mt-4 flex gap-2"><Button variant={locale === "en" ? "default" : "outline"} onClick={() => setLocale("en")} className={locale === "en" ? "bg-slate-900 text-white hover:bg-slate-800" : ""}>English</Button><Button variant={locale === "ar" ? "default" : "outline"} onClick={() => setLocale("ar")} className={locale === "ar" ? "bg-slate-900 text-white hover:bg-slate-800" : ""}>العربية</Button></div></div></div></Card><Card className="ns-surface p-6 shadow-sm"><div className="flex items-start gap-4"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-50 text-emerald-700"><UserRound className="h-5 w-5" /></div><div className="min-w-0 flex-1"><h2 className="text-xl font-semibold text-slate-950">{t("accountSettings")}</h2><p className="mt-1 text-sm text-slate-600">{t("identityContext")}</p><Link href="/profile"><Button variant="outline" className="mt-4">{t("openProfile")}</Button></Link></div></div></Card></div></div></div>;
}
