import { createContext, useContext, useEffect, useMemo, useState } from "react";

type Locale = "en" | "ar";

const copy = {
  en: {
    explore: "Explore",
    search: "Search",
    collections: "Collections",
    graph: "Graph",
    signIn: "Sign in",
    profile: "Profile",
    moderation: "Moderation",
    logOut: "Log out",
    submit: "Submit a resource",
    commandSearch: "Search pages and actions…",
    signInRequired: "Sign in required",
    signInToViewProfile: "Sign in to view profile",
    browseResources: "Browse resources",
    member: "Member",
    administrator: "Administrator",
    reputation: "reputation",
    editProfile: "Edit profile",
    yourNorthStarPath: "Your NorthStar path",
    pathHeading: "Turn activity into useful community context.",
    pathDescription: "These steps are optional, but they make your contributions easier to understand, verify, and revisit.",
    started: "started",
    profileContextAdded: "Profile context added",
    addProfileContext: "Add profile context",
    keepIdentityCurrent: "Keep your identity current for collaborators.",
    shareWhatExplore: "Share what you explore or build.",
    buildPersonalMap: "Build a personal map",
    saveResources: "Save resources and assemble reusable stacks.",
    keepContributing: "Keep contributing",
    makeFirstContribution: "Make a first contribution",
    everySubmissionHuman: "Every submission enters human moderation.",
    editYourProfile: "Edit your profile",
    identityContext: "Keep your identity and context current for the community.",
    displayName: "Display name",
    avatarUrl: "Avatar URL",
    bio: "Bio",
    bioPlaceholder: "What do you explore or build?",
    cancel: "Cancel",
    saving: "Saving…",
    saveProfile: "Save profile",
    reputationActivity: "Reputation activity",
    verifiedContributionSignals: "A transparent record of verified contribution signals.",
    contributions: "Contributions",
    collectionsTab: "Collections",
    bookmarks: "Bookmarks",
    approved: "Approved",
    needsRevision: "Needs revision",
    pendingModeration: "Pending moderation",
    published: "Published",
    inReview: "In review",
    submitFirstResource: "Submit your first resource",
    yourCollections: "Your collections",
    curateStacks: "Curate reusable stacks of resources for yourself or the community.",
    newCollection: "New collection",
    public: "Public",
    private: "Private",
    noDescription: "No description yet.",
    openCollection: "Open collection",
    noCollections: "You haven’t created any collections yet.",
    createFirstCollection: "Create your first collection",
    humanOversight: "Human oversight",
    moderationCommandCenter: "Moderation command center",
    moderationIntro: "Review resource submissions, graph suggestions, and community signals before they become part of NorthStar’s public knowledge layer.",
    submissions: "Submissions",
    graphEdges: "Graph edges",
    reportTriage: "Report triage",
    reportTriageDetail: "Assess community quality concerns",
    bulkDecisions: "Bulk decisions",
    bulkDecisionsDetail: "Reject selected pending submissions safely",
    editSuggestions: "Edit suggestions",
    editSuggestionsDetail: "Review contributor corrections",
    aiReviewDrafts: "AI review drafts",
    aiReviewDraftsDetail: "Generate non-publishing context",
    userManagement: "User management",
    userManagementDetail: "Manage platform roles safely",
    relationships: "Relationships",
    resources: "Resources",
    history: "History",
    pending: "Pending",
    approve: "Approve",
    reject: "Reject",
    pendingGraphEdge: "Pending graph edge",
    moderationHistory: "Moderation history",
    moderationHistoryDetail: "A read-only record of recent moderation actions.",
    report: "Report",
    reportConcern: "Report a resource concern",
    reportExplanation: "Your report is sent to moderators for review. It does not automatically alter this resource.",
    reportSubmitted: "Report submitted for moderator review",
    unableToSubmitReport: "Unable to submit report",
    reportReason: "Reason",
    spamOrPromotional: "Spam or promotional content",
    duplicateResource: "Duplicate resource",
    inaccurateOrOutdated: "Inaccurate or outdated information",
    potentiallyMalicious: "Potentially malicious destination",
    otherQualityConcern: "Other quality concern",
    suspectedDuplicate: "Suspected duplicate",
    details: "Details",
    optional: "optional",
    duplicateDetailsRequired: "Add the suspected duplicate resource name or URL for the moderator.",
    duplicateDetailsPlaceholder: "Add the duplicate resource’s NorthStar URL, official URL, or name.",
    reportDetailsPlaceholder: "Share enough context for a moderator to assess the concern.",
    submitting: "Submitting",
    submitReport: "Submit report",
    suggestEdit: "Suggest edit",
    suggestCorrection: "Suggest a resource correction",
    suggestionExplanation: "Your proposal is reviewed by a moderator before any public resource data changes.",
    editSuggestionSent: "Edit suggestion sent for human review",
    unableToSendSuggestion: "Unable to send edit suggestion",
    changeAtLeastOneField: "Change at least one field before submitting",
    title: "Title",
    description: "Description",
    officialUrl: "Official URL",
    builtBy: "Built by",
    correctionReason: "Why is this correction needed?",
    correctionPlaceholder: "Share a source or helpful context for the reviewer.",
    sending: "Sending",
    sendSuggestion: "Send suggestion",
    curatedKnowledge: "Curated knowledge",
    loadingStacks: "Loading stacks",
    shareable: "shareable",
    createCollection: "Create a collection",
    collectionName: "Name",
    visibility: "Visibility",
    collectionDescription: "Description",
    collectionDescriptionPlaceholder: "What will people learn from this stack?",
    creating: "Creating…",
    open: "Open",
    updated: "Updated",
    collectionNotFound: "Collection not found",
    collectionUnavailable: "This collection may be private or no longer available.",
    backToCollections: "Back to collections",
    allCollections: "All collections",
    copyShareLink: "Copy share link",
    linkCopied: "Link copied",
    edit: "Edit",
    saveChanges: "Save changes",
    deleteCollection: "Delete collection",
    deleteCollectionConfirm: "Delete this collection? This cannot be undone.",
    removeFromCollection: "Remove from collection",
    removeResourceConfirm: "Remove this resource from the collection?",
    knowledgeStack: "Knowledge stack",
    resourcesInCollection: "Resources in this collection",
    collectionEmpty: "This collection is empty",
    collectionEmptyDescription: "Open a resource and add it to this stack to make the collection useful.",
    curatedResourceSet: "A curated set of resources.",
    noCollectionsYet: "No collections yet",
    noCollectionsDescription: "Create your first collection to turn individual resources into a navigable knowledge stack.",
    failedToSubmitResource: "Failed to submit resource",
    validSubmissionRequired: "Add a valid URL, title, and category before submitting.",
    reviewPossibleDuplicates: "Review the possible duplicates before submitting this resource.",
    signInToContribute: "Sign in to contribute",
    contributionReview: "Contributions are reviewed by the community and moderators before publication.",
    submissionReceived: "Submission received",
    submissionThanks: "Thank you. A moderator will review the resource before it appears in the public directory.",
    submitAnother: "Submit another",
    communityContribution: "Community contribution",
    submitResourceIntro: "Help the community discover a useful tool. We’ll fetch metadata, check for duplicates, and route the contribution through moderation.",
    startWithUrl: "Start with a URL",
    metadataPrefill: "We use the public page to prefill what we can.",
    resourceUrl: "Resource URL",
    metadataUnavailable: "We couldn’t fetch metadata. You can still complete the fields manually.",
    metadataLoaded: "Metadata preview loaded from",
    resourceTitle: "Resource title",
    resourceDescriptionPlaceholder: "What problem does it solve, and who should use it?",
    possibleDuplicates: "Possible duplicates found",
    duplicatesGuidance: "Review these existing resources before submitting.",
    pendingReview: "Pending review",
    view: "View",
    classifyResource: "Classify the resource",
    category: "Category",
    subcategory: "Subcategory",
    pricingModel: "Pricing model",
    selectCategory: "Select a category",
    selectSubcategory: "Select a subcategory",
    noSubcategories: "No subcategories",
    builderUrl: "Builder URL",
    tags: "Tags",
    separateTags: "Separate tags with commas.",
    graphConnections: "Suggest graph connections",
    graphSuggestionGuidance: "These suggestions go to moderation with your submission. They are not published automatically.",
    searchExistingResource: "Search an existing resource",
    addFirstMatch: "Add first match",
    evidenceUrlOptional: "Evidence URL (optional)",
    sourceContextOptional: "Source context, e.g. project docs (optional)",
    relationshipRationalePlaceholder: "Why is this relationship meaningful? Add enough context for a moderator to verify it. (optional)",
    matches: "Matches",
    evidenceSupplied: "Evidence supplied",
    removeSuggestedRelationship: "Remove suggested relationship",
    reviewBeforeSubmitting: "Review before submitting",
    moderationPayload: "This is the exact resource payload that will enter human moderation.",
    noDescriptionProvided: "No description provided.",
    noTags: "No tags",
    suggestedRelationships: "Suggested relationships",
    none: "None",
    editDetails: "Edit details",
    sendingToModeration: "Sending to moderation…",
    submitForReview: "Submit for review",
    alternativeTo: "Alternative To",
    similarTo: "Similar To",
    integratesWith: "Integrates With",
    maintainedBy: "Maintained By",
    fundedBy: "Funded By",
    usedBy: "Used By",
    dependsOn: "Depends On",
    partOf: "Part Of",
    competitorOf: "Competitor Of",
    resourceDirectory: "Resource directory",
    browseHub: "Browse the intelligence hub",
    browseIntro: "Search and filter verified tools, services, libraries, and ecosystems with context that helps you choose well.",
    refineGraph: "Refine the resource graph with focused filters.",
    hideFilters: "Hide filters",
    filtersActive: "Filters active",
    filters: "Filters",
    clearAll: "Clear all",
    searchResources: "Search resources…",
    categories: "Categories",
    allResources: "All resources",
    loadingCategories: "Loading categories",
    subcategories: "Subcategories",
    allSubcategories: "All subcategories",
    allPricing: "All pricing",
    free: "Free",
    paid: "Paid",
    openSource: "Open source",
    enterprise: "Enterprise",
    tag: "Tag",
    updatingResults: "Updating results…",
    showing: "Showing",
    of: "of",
    sortResources: "Sort resources",
    mostPopular: "Most popular",
    newest: "Newest",
    gridView: "Grid view",
    listView: "List view",
    unableToLoadResources: "We couldn’t load resources",
    tryAgain: "Please try again in a moment.",
    noMatchingResources: "No matching resources",
    broadenSearch: "Try a broader search or clear one of the filters.",
    clearFilters: "Clear filters",
    uncategorized: "Uncategorized",
    featured: "Featured",
    noDescriptionAdded: "No description has been added yet.",
    previous: "Previous",
    next: "Next",
    page: "Page",
    relationshipDiscovery: "Relationship-aware discovery",
    connectionMatters: "Find the connection that matters.",
    searchIntro: "Search by tool, need, or relationship. NorthStar interprets the context around alternatives, integrations, competitors, and similar resources.",
    searchExample: "Try “Jira alternatives” or “Slack integrations”",
    alternatives: "Alternatives",
    integrations: "Integrations",
    competitors: "Competitors",
    ecosystem: "Ecosystem",
    similarTools: "Similar tools",
    searchResults: "Search results",
    resultsFor: "Results for",
    results: "Results",
    suggestions: "Suggestions",
    allCategories: "All categories",
    pricing: "Pricing",
    clear: "Clear",
    trendingGraph: "Trending in the graph",
    liveSignal: "Start with a live resource signal.",
    liveTrendsEmpty: "Live trend signals will appear here as the graph grows.",
    exploreRelationship: "Explore a relationship",
    relationshipIntentHelp: "Use plain language; NorthStar recognizes common graph intents.",
    openGraphQuery: "Open graph query",
    noResourcesMatched: "No resources matched",
    searchNoResults: "Try a broader term, clear a filter, or browse the directory.",
    resourceNode: "Resource node",
    resourceGraphDescription: "Explore this resource and its verified graph connections.",
    knowledgeGraphNode: "Knowledge graph node",
    openNode: "Open node",
    keepTyping: "Keep typing to surface resource and relationship suggestions.",
    resourceSuggestions: "Resource suggestions",
    relatedQueries: "Related queries",
    relationshipVoteSaved: "Relationship vote saved",
    relationshipVoteError: "We couldn’t save your relationship vote. Please try again.",
    connectedResource: "Explore this connected resource.",
    strength: "strength",
    verifiedRelationship: "Verified relationship",
    connectionUseful: "Is this connection useful?",
    upvote: "Upvote",
    downvote: "Downvote",
    resourceNotFound: "Resource not found",
    resourceUnavailable: "This resource may have been removed or is still awaiting approval.",
    backToBrowse: "Back to browse",
    saved: "Saved",
    save: "Save",
    openGraph: "Open graph",
    copied: "Copied",
    copyLink: "Copy link",
    share: "Share",
    visitResource: "Visit resource",
    voteSaved: "Your vote was saved",
    voteError: "We couldn’t save your vote. Please try again.",
    resourceSaved: "Resource saved",
    resourceRemoved: "Resource removed from saved items",
    savedItemsError: "We couldn’t update your saved items. Please try again.",
    chooseCollectionFirst: "Choose a collection first",
    resourceAddedToCollection: "Resource added to collection",
    addToCollectionError: "Could not add this resource to the collection.",
    copyLinkError: "We couldn’t copy the link",
    nativeShareUnavailable: "Native sharing is unavailable; the link was copied instead.",
    shareDialogError: "We couldn’t open the share dialog",
    connections: "connections",
    relationshipTypes: "relationship types",
    communitySignal: "Community signal",
    upvotes: "upvotes",
    knowledgeGraph: "Knowledge graph",
    exploreConnected: "Explore connected resources",
    noVerifiedConnections: "No verified connections yet",
    relationshipAfterModeration: "Community relationships will appear here after moderation.",
    communityFeedback: "Community feedback",
    feedbackGuidance: "Vote on whether this resource is useful to the community.",
    signInToVote: "Sign in to vote or save this resource.",
    organizeResource: "Organize this resource",
    organizeGuidance: "Add this node to a curated stack so you can revisit it with related tools.",
    chooseCollection: "Choose a collection",
    adding: "Adding…",
    addToCollection: "Add to collection",
    createOne: "Create one",
    organizeSignIn: "Sign in to organize resources into collections.",
    resourceDetails: "Resource details",
    views: "Views",
    notSpecified: "Not specified",
    unknown: "Unknown",
    trustContext: "Trust context",
    evidenceSources: "Approved evidence",
    publicHistory: "Public history",
    freshness: "Freshness",
    lastChecked: "Last checked",
    noApprovedEvidence: "No approved evidence has been added yet.",
    noPublicHistory: "No public change history yet.",
    current: "Current",
    needsReview: "Needs review",
    stale: "Stale",
    submitSource: "Add evidence",
    submitSourceIntro: "Share a public source that helps the community verify this resource. A moderator reviews every submission before it is shown publicly.",
    sourceType: "Source type",
    sourceUrl: "Source URL",
    sourceAttribution: "Attribution",
    sourceLicenseNote: "License or reuse note",
    sourceSubmitted: "Evidence submitted for moderator review.",
    sourceSubmitError: "We could not submit this evidence. Please check the link and try again.",
    sourceTypeOfficial: "Official site",
    sourceTypeDocumentation: "Documentation",
    sourceTypeRepository: "Repository",
    sourceTypeCommunity: "Community reference",
    sourceTypeArchive: "Archive",
    sourceTypeOther: "Other public source",
    pendingSources: "Evidence queue",
    freshnessQueue: "Freshness queue",
    duplicateProposals: "Duplicate proposals",
    reviewSource: "Review evidence",
    approveSource: "Approve evidence",
    rejectSource: "Reject evidence",
    supersedeSource: "Supersede evidence",
    recordFreshness: "Record freshness",
    freshnessNote: "Freshness note",
    proposeAlias: "Propose canonical alias",
    confirmAlias: "Confirm canonical alias",
    aliasConfirmed: "Canonical alias confirmed.",
    aliasNotice: "This resource is an archived duplicate. Continue to the verified canonical resource.",
    noPendingSources: "No evidence sources are waiting for review.",
    noFreshnessItems: "No approved resources need a freshness review right now.",
    noDuplicateProposals: "No duplicate-alias proposals are waiting for confirmation.",
    reviewedBy: "Submitted by",
    noFreshnessReview: "No freshness review recorded",
    confirmAliasDetail: "Confirmation preserves the duplicate record and its community references; it does not delete or silently rewrite data.",
    switchToDark: "Switch to dark theme",
    switchToLight: "Switch to light theme",
    collectionDiscovery: "Community stacks",
    collectionDiscoveryIntro: "Explore public, reusable collections that preserve context around tools and workflows.",
    myCollections: "My collections",
    collectionOwner: "Curated by",
    resourceCount: "resources",
    noPublicCollections: "No public collections are available yet.",
    signInToCreateCollection: "Sign in to create and manage collections.",
    trending: "Trending",
    trendingIntro: "A lightweight view of public resource momentum, based on the platform’s current usefulness signals.",
    popularNow: "Popular now",
    trendingEmpty: "No public popularity signals are available yet. Explore the directory to start building context.",
    exploreMore: "Explore more resources",
    about: "About",
    aboutIntro: "NorthStar is an open resource intelligence platform for discovering tools in their wider ecosystem.",
    aboutMission: "A directory with context",
    aboutMissionText: "NorthStar treats every resource as a knowledge object with metadata, relationships, provenance, and room for community review.",
    aboutPrinciples: "Product principles",
    developer: "Developers",
    developerIntro: "NorthStar is designed to remain transparent, extensible, and safe for community contribution.",
    apiBoundary: "Current API boundary",
    apiBoundaryText: "The production application currently uses internal typed contracts. A versioned public REST API and OpenAPI specification are planned but are not yet available.",
    readApiDocs: "Read API boundary documentation",
    openSourceCollaboration: "Open-source collaboration",
    openSourceText: "Explore the repository, contribute through the documented governance process, and never treat automated enrichment as a source of truth.",
    settings: "Settings",
    settingsIntro: "Control your local NorthStar preferences. These choices stay in this browser.",
    appearance: "Appearance",
    language: "Language",
    accountSettings: "Account",
    openProfile: "Open profile",
    lightTheme: "Light theme",
    darkTheme: "Dark theme",
    resourceIntelligenceNotLinks: "Resource intelligence, not link collecting",
    discoverResourcesContext: "Discover resources in context.",
    homeHeroDescription: "NorthStar connects digital tools through verified relationships, so every search can lead to alternatives, integrations, dependencies, and the surrounding ecosystem.",
    homeSearchPlaceholder: "Try “Jira alternatives” or “Figma integrations”",
    homeSearchAria: "Search the NorthStar resource graph",
    relationshipShortcuts: "Relationship-aware shortcuts:",
    exploreResources: "Explore resources",
    contributeResource: "Contribute a resource",
    connectedKnowledgeObject: "Connected knowledge object",
    verifiedGraph: "Verified graph",
    designCollaboration: "Design & collaboration",
    homeFigmaDescription: "A collaborative design platform with a discoverable relationship map.",
    signals: "Signals",
    builtForGraphNavigation: "Built for graph navigation",
    discoveryPaths: "Discovery paths",
    homeQuestionTitle: "Start with the question you have.",
    openRelationshipSearch: "Open relationship search",
    findRightTool: "Find the right tool",
    findToolDescription: "Search by name, use case, category, or the relationship you want to understand.",
    searchGraph: "Search the graph",
    traceConnections: "Trace the connections",
    traceConnectionsDescription: "Move from a resource to its alternatives, integrations, competitors, and ecosystem.",
    browseNodes: "Browse nodes",
    buildUsefulStack: "Build a useful stack",
    buildStackDescription: "Save, curate, and share collections that preserve the context behind your choices.",
    viewCollections: "View collections",
    graphBenefits: "How the graph helps",
    graphBenefitsTitle: "A calmer way to evaluate a crowded tool landscape.",
    graphBenefitsDescription: "NorthStar turns a directory into an intelligence layer. Each resource is designed to carry clear metadata, relationship context, community signals, and a route into its broader ecosystem.",
    understandTradeoffs: "Understand trade-offs",
    tradeoffsDescription: "Compare credible alternatives without restarting research from scratch.",
    discoverConnections: "Discover connections",
    connectionsDescription: "Surface integrations and dependencies that affect real workflows.",
    keepKnowledgeReusable: "Keep knowledge reusable",
    knowledgeReusableDescription: "Turn individual findings into collections your team can revisit.",
    contributeWithReview: "Contribute with review",
    contributeReviewDescription: "Submit resources and relationship suggestions through a human moderation loop.",
    makeGraphStronger: "Make the graph stronger",
    graphStrongerTitle: "Have a resource or relationship worth mapping?",
    graphStrongerDescription: "Contributions are reviewed by people before they become public knowledge. Start with a resource, then add the context that makes it useful.",
    submitAResource: "Submit a resource",
    graphExplorerKicker: "Knowledge graph",
    graphExplorerTitle: "Explore a resource ecosystem",
    graphExplorerDescription: "Choose a resource to inspect its verified, one-hop relationship neighborhood. Every connection remains available as an accessible list below the visual map.",
    graphFindResource: "Find a resource to explore",
    graphSearchPlaceholder: "Search a resource, e.g. Figma or GitHub",
    graphMatchHeading: "Resource matches",
    graphResourceFallbackDescription: "Explore this resource’s knowledge graph.",
    graphNoMatch: "No approved resources match that search.",
    graphUnavailable: "Resource graph unavailable",
    graphUnavailableDescription: "The resource may be unavailable or awaiting approval.",
    graphChooseOther: "Choose another resource",
    graphBackToNode: "Back to Node View",
    graphExploreOther: "Explore another node",
    graphOneHop: "One-hop graph explorer",
    graphEcosystemSuffix: "ecosystem",
    graphBoundedDescription: "Showing up to 40 approved relationship edges and 12 adjacent resource nodes. This view is deliberately bounded for clarity and performance.",
    graphRelationshipMap: "relationship map",
    graphFocusNode: "Focus node",
    graphAccessibleList: "Accessible relationship list",
    graphAccessibleListDescription: "Use this semantic list to inspect every visible edge, its direction, verification status, and evidence context.",
    graphOutgoingConnection: "Outgoing connection from",
    graphIncomingConnection: "Incoming connection to",
    graphStrength: "strength",
    graphVerified: "Verified",
    graphPendingVerification: "Pending verification",
    graphEvidence: "Evidence",
    graphNoEdges: "No approved edges yet",
    graphNoEdgesDescription: "Community-suggested connections appear here after human moderation.",
    apiKeys: "API keys",
    apiKeyIntro: "Create a read-only key for a specific integration. Keep it secret: NorthStar shows the full key only once.",
    createApiKey: "Create API key",
    apiKeyName: "Key name",
    apiKeyNamePlaceholder: "e.g. Internal research client",
    apiScopes: "Read scopes",
    dailyQuota: "Daily request quota",
    apiKeySecretWarning: "Copy this key now. It cannot be shown again after you close this notice.",
    copyKey: "Copy key",
    copiedKey: "API key copied",
    revokeKey: "Revoke key",
    revoked: "Revoked",
    active: "Active",
    noApiKeys: "No API keys have been created yet.",
    apiUsageToday: "Usage today",
    remainingRequests: "requests remaining",
    noExpiry: "No expiry",
    signInToManageApi: "Sign in to create and manage your API keys.",
    searchQuality: "Search quality",
    searchQualityIntro: "Privacy-safe aggregate signals and human-reviewed relevance cases. Metrics do not retain user, session, or IP identifiers.",
    searchVolume: "Searches",
    zeroResultRate: "Zero-result rate",
    clickThroughRate: "Click-through rate",
    reformulationRate: "Reformulation rate",
    averageLatency: "Average latency",
    relevanceCases: "Relevance cases",
    createEvaluationCase: "Create relevance case",
    expectedResourceIds: "Expected resource IDs",
    expectedResourceIdsHelp: "Use comma-separated resource IDs that a human reviewer has judged relevant.",
    caseNotes: "Review notes",
    draft: "Draft",
    noRelevanceCases: "No human-authored relevance cases exist yet.",
    qualityAccessDenied: "Search quality is available to moderators and administrators.",
    importResources: "Import resources from a file or chat export",
    importResourcesIntro: "Drop a WhatsApp export, text file, PDF, Office document, spreadsheet, presentation, or image. NorthStar extracts links in memory only.",
    importPrivacy: "Personal data, chat messages, sender details, timestamps, and the source file are discarded. Only safe resource URLs can continue to review.",
    chooseFile: "Choose a file",
    dropFile: "Drop a supported file here",
    processingImport: "Extracting resource links…",
    importResults: "Import results",
    foundCandidates: "safe resource candidates found",
    rejectedLinks: "unsafe or invalid links excluded",
    useCandidate: "Use this resource",
    imageOcrLocal: "Image OCR is completed locally before any detected link is sent for review.",
    personalDataDiscarded: "No personal data was retained.",
  },
  ar: {
    explore: "استكشاف",
    search: "بحث",
    collections: "المجموعات",
    graph: "الرسم البياني",
    signIn: "تسجيل الدخول",
    profile: "الملف الشخصي",
    moderation: "الإشراف",
    logOut: "تسجيل الخروج",
    submit: "إضافة مورد",
    commandSearch: "ابحث في الصفحات والإجراءات…",
    signInRequired: "تسجيل الدخول مطلوب",
    signInToViewProfile: "سجّل الدخول لعرض الملف الشخصي",
    browseResources: "استكشاف الموارد",
    member: "عضو",
    administrator: "مدير",
    reputation: "سمعة",
    editProfile: "تعديل الملف الشخصي",
    yourNorthStarPath: "مسارك في نورث ستار",
    pathHeading: "حوّل نشاطك إلى سياق مجتمعي مفيد.",
    pathDescription: "هذه الخطوات اختيارية، لكنها تجعل مساهماتك أسهل للفهم والتحقق والعودة إليها.",
    started: "مكتملة",
    profileContextAdded: "تمت إضافة سياق الملف",
    addProfileContext: "أضف سياقاً لملفك",
    keepIdentityCurrent: "حافظ على معلوماتك محدثة للمتعاونين.",
    shareWhatExplore: "شارك ما تستكشفه أو تبنيه.",
    buildPersonalMap: "ابنِ خريطتك الشخصية",
    saveResources: "احفظ الموارد وأنشئ مجموعات قابلة لإعادة الاستخدام.",
    keepContributing: "واصل المساهمة",
    makeFirstContribution: "قدّم أول مساهمة",
    everySubmissionHuman: "تدخل كل مساهمة في مراجعة بشرية.",
    editYourProfile: "عدّل ملفك الشخصي",
    identityContext: "حافظ على هويتك وسياقك محدثين للمجتمع.",
    displayName: "الاسم الظاهر",
    avatarUrl: "رابط الصورة الشخصية",
    bio: "نبذة",
    bioPlaceholder: "ما الذي تستكشفه أو تبنيه؟",
    cancel: "إلغاء",
    saving: "جارٍ الحفظ…",
    saveProfile: "حفظ الملف الشخصي",
    reputationActivity: "نشاط السمعة",
    verifiedContributionSignals: "سجل شفاف لإشارات المساهمة التي تم التحقق منها.",
    contributions: "المساهمات",
    collectionsTab: "المجموعات",
    bookmarks: "المحفوظات",
    approved: "مقبول",
    needsRevision: "يحتاج إلى تعديل",
    pendingModeration: "بانتظار الإشراف",
    published: "منشور",
    inReview: "قيد المراجعة",
    submitFirstResource: "أضف أول مورد لك",
    yourCollections: "مجموعاتك",
    curateStacks: "نظّم مجموعات موارد قابلة لإعادة الاستخدام لك أو للمجتمع.",
    newCollection: "مجموعة جديدة",
    public: "عامة",
    private: "خاصة",
    noDescription: "لا يوجد وصف بعد.",
    openCollection: "فتح المجموعة",
    noCollections: "لم تنشئ أي مجموعات بعد.",
    createFirstCollection: "أنشئ أول مجموعة لك",
    humanOversight: "إشراف بشري",
    moderationCommandCenter: "مركز قيادة الإشراف",
    moderationIntro: "راجع طلبات الموارد واقتراحات الرسم البياني وإشارات المجتمع قبل إضافتها إلى طبقة المعرفة العامة في نورث ستار.",
    submissions: "الطلبات",
    graphEdges: "روابط الرسم البياني",
    reportTriage: "فرز البلاغات",
    reportTriageDetail: "تقييم مخاوف جودة المجتمع",
    bulkDecisions: "قرارات جماعية",
    bulkDecisionsDetail: "رفض الطلبات المحددة بأمان",
    editSuggestions: "اقتراحات التعديل",
    editSuggestionsDetail: "مراجعة تصحيحات المساهمين",
    aiReviewDrafts: "مسودات مراجعة الذكاء الاصطناعي",
    aiReviewDraftsDetail: "إنشاء سياق لا ينشر تلقائياً",
    userManagement: "إدارة المستخدمين",
    userManagementDetail: "إدارة أدوار المنصة بأمان",
    relationships: "العلاقات",
    resources: "الموارد",
    history: "السجل",
    pending: "قيد الانتظار",
    approve: "موافقة",
    reject: "رفض",
    pendingGraphEdge: "رابط رسم بياني قيد المراجعة",
    moderationHistory: "سجل الإشراف",
    moderationHistoryDetail: "سجل للقراءة فقط لأحدث إجراءات الإشراف.",
    report: "إبلاغ",
    reportConcern: "الإبلاغ عن مشكلة في مورد",
    reportExplanation: "يُرسل بلاغك إلى المشرفين للمراجعة ولا يغير هذا المورد تلقائياً.",
    reportSubmitted: "تم إرسال البلاغ لمراجعة المشرفين",
    unableToSubmitReport: "تعذر إرسال البلاغ",
    reportReason: "السبب",
    spamOrPromotional: "محتوى مزعج أو ترويجي",
    duplicateResource: "مورد مكرر",
    inaccurateOrOutdated: "معلومات غير دقيقة أو قديمة",
    potentiallyMalicious: "وجهة قد تكون ضارة",
    otherQualityConcern: "ملاحظة أخرى تتعلق بالجودة",
    suspectedDuplicate: "المورد المكرر المحتمل",
    details: "التفاصيل",
    optional: "اختياري",
    duplicateDetailsRequired: "أضف اسم المورد المكرر المحتمل أو رابطه ليتمكن المشرف من مراجعته.",
    duplicateDetailsPlaceholder: "أضف رابط المورد في نورث ستار أو رابطه الرسمي أو اسمه.",
    reportDetailsPlaceholder: "شارك سياقاً كافياً ليتمكن المشرف من تقييم الملاحظة.",
    submitting: "جارٍ الإرسال",
    submitReport: "إرسال البلاغ",
    suggestEdit: "اقترح تعديلاً",
    suggestCorrection: "اقترح تصحيحاً للمورد",
    suggestionExplanation: "يراجع المشرف اقتراحك قبل تغيير أي بيانات عامة للمورد.",
    editSuggestionSent: "تم إرسال اقتراح التعديل للمراجعة البشرية",
    unableToSendSuggestion: "تعذر إرسال اقتراح التعديل",
    changeAtLeastOneField: "غيّر حقلاً واحداً على الأقل قبل الإرسال",
    title: "العنوان",
    description: "الوصف",
    officialUrl: "الرابط الرسمي",
    builtBy: "الجهة المطورة",
    correctionReason: "لماذا يحتاج هذا التصحيح؟",
    correctionPlaceholder: "شارك مصدراً أو سياقاً مفيداً للمراجع.",
    sending: "جارٍ الإرسال",
    sendSuggestion: "إرسال الاقتراح",
    curatedKnowledge: "معرفة منسقة",
    loadingStacks: "جارٍ تحميل المجموعات",
    shareable: "قابلة للمشاركة",
    createCollection: "إنشاء مجموعة",
    collectionName: "الاسم",
    visibility: "الظهور",
    collectionDescription: "الوصف",
    collectionDescriptionPlaceholder: "ماذا سيتعلم الناس من هذه المجموعة؟",
    creating: "جارٍ الإنشاء…",
    open: "فتح",
    updated: "تم التحديث",
    collectionNotFound: "لم يتم العثور على المجموعة",
    collectionUnavailable: "قد تكون هذه المجموعة خاصة أو لم تعد متاحة.",
    backToCollections: "العودة إلى المجموعات",
    allCollections: "كل المجموعات",
    copyShareLink: "نسخ رابط المشاركة",
    linkCopied: "تم نسخ الرابط",
    edit: "تعديل",
    saveChanges: "حفظ التغييرات",
    deleteCollection: "حذف المجموعة",
    deleteCollectionConfirm: "هل تريد حذف هذه المجموعة؟ لا يمكن التراجع عن ذلك.",
    removeFromCollection: "إزالة من المجموعة",
    removeResourceConfirm: "هل تريد إزالة هذا المورد من المجموعة؟",
    knowledgeStack: "مجموعة معرفية",
    resourcesInCollection: "الموارد في هذه المجموعة",
    collectionEmpty: "هذه المجموعة فارغة",
    collectionEmptyDescription: "افتح مورداً وأضفه إلى هذه المجموعة لتصبح أكثر فائدة.",
    curatedResourceSet: "مجموعة منسقة من الموارد.",
    noCollectionsYet: "لا توجد مجموعات بعد",
    noCollectionsDescription: "أنشئ مجموعتك الأولى لتحويل الموارد الفردية إلى مجموعة معرفية قابلة للتنقل.",
    failedToSubmitResource: "تعذر إرسال المورد",
    validSubmissionRequired: "أضف رابطاً صالحاً وعنواناً وفئة قبل الإرسال.",
    reviewPossibleDuplicates: "راجع الموارد المكررة المحتملة قبل إرسال هذا المورد.",
    signInToContribute: "سجّل الدخول للمساهمة",
    contributionReview: "تخضع المساهمات لمراجعة المجتمع والمشرفين قبل النشر.",
    submissionReceived: "تم استلام الطلب",
    submissionThanks: "شكراً لك. سيراجع مشرف المورد قبل ظهوره في الدليل العام.",
    submitAnother: "إرسال مورد آخر",
    communityContribution: "مساهمة مجتمعية",
    submitResourceIntro: "ساعد المجتمع على اكتشاف أداة مفيدة. سنجلب البيانات الوصفية ونتحقق من التكرار ونرسل المساهمة للمراجعة.",
    startWithUrl: "ابدأ برابط",
    metadataPrefill: "نستخدم الصفحة العامة لملء ما نستطيع مسبقاً.",
    resourceUrl: "رابط المورد",
    metadataUnavailable: "تعذر جلب البيانات الوصفية. لا يزال بإمكانك إكمال الحقول يدوياً.",
    metadataLoaded: "تم تحميل معاينة البيانات الوصفية من",
    resourceTitle: "عنوان المورد",
    resourceDescriptionPlaceholder: "ما المشكلة التي يحلها؟ ولمن يفيد؟",
    possibleDuplicates: "تم العثور على موارد مكررة محتملة",
    duplicatesGuidance: "راجع هذه الموارد الحالية قبل الإرسال.",
    pendingReview: "بانتظار المراجعة",
    view: "عرض",
    classifyResource: "صنّف المورد",
    category: "الفئة",
    subcategory: "الفئة الفرعية",
    pricingModel: "نموذج التسعير",
    selectCategory: "اختر فئة",
    selectSubcategory: "اختر فئة فرعية",
    noSubcategories: "لا توجد فئات فرعية",
    builderUrl: "رابط الجهة المطورة",
    tags: "الوسوم",
    separateTags: "افصل بين الوسوم بفواصل.",
    graphConnections: "اقترح علاقات في الرسم البياني",
    graphSuggestionGuidance: "تذهب هذه الاقتراحات إلى الإشراف مع طلبك ولا تُنشر تلقائياً.",
    searchExistingResource: "ابحث عن مورد موجود",
    addFirstMatch: "أضف أول تطابق",
    evidenceUrlOptional: "رابط الدليل (اختياري)",
    sourceContextOptional: "سياق المصدر، مثل وثائق المشروع (اختياري)",
    relationshipRationalePlaceholder: "لماذا هذه العلاقة ذات معنى؟ أضف سياقاً كافياً ليتمكن المشرف من التحقق منها. (اختياري)",
    matches: "التطابقات",
    evidenceSupplied: "تم تقديم دليل",
    removeSuggestedRelationship: "إزالة العلاقة المقترحة",
    reviewBeforeSubmitting: "راجع قبل الإرسال",
    moderationPayload: "هذه هي بيانات المورد الدقيقة التي ستدخل المراجعة البشرية.",
    noDescriptionProvided: "لم يتم تقديم وصف.",
    noTags: "لا توجد وسوم",
    suggestedRelationships: "العلاقات المقترحة",
    none: "لا شيء",
    editDetails: "تعديل التفاصيل",
    sendingToModeration: "جارٍ الإرسال إلى الإشراف…",
    submitForReview: "إرسال للمراجعة",
    alternativeTo: "بديل لـ",
    similarTo: "مشابه لـ",
    integratesWith: "يتكامل مع",
    maintainedBy: "تتم صيانته بواسطة",
    fundedBy: "ممول بواسطة",
    usedBy: "يُستخدم بواسطة",
    dependsOn: "يعتمد على",
    partOf: "جزء من",
    competitorOf: "منافس لـ",
    resourceDirectory: "دليل الموارد",
    browseHub: "استكشف مركز المعرفة",
    browseIntro: "ابحث في الأدوات والخدمات والمكتبات والأنظمة البيئية الموثقة وصفّها مع سياق يساعدك على الاختيار الجيد.",
    refineGraph: "حسّن رسم الموارد باستخدام عوامل تصفية مركزة.",
    hideFilters: "إخفاء عوامل التصفية",
    filtersActive: "عوامل التصفية نشطة",
    filters: "عوامل التصفية",
    clearAll: "مسح الكل",
    searchResources: "ابحث عن الموارد…",
    categories: "الفئات",
    allResources: "كل الموارد",
    loadingCategories: "جارٍ تحميل الفئات",
    subcategories: "الفئات الفرعية",
    allSubcategories: "كل الفئات الفرعية",
    allPricing: "كل الأسعار",
    free: "مجاني",
    paid: "مدفوع",
    openSource: "مفتوح المصدر",
    enterprise: "مؤسسات",
    tag: "وسم",
    updatingResults: "جارٍ تحديث النتائج…",
    showing: "عرض",
    of: "من",
    sortResources: "ترتيب الموارد",
    mostPopular: "الأكثر شيوعاً",
    newest: "الأحدث",
    gridView: "عرض شبكي",
    listView: "عرض قائمة",
    unableToLoadResources: "تعذر تحميل الموارد",
    tryAgain: "يرجى المحاولة مرة أخرى بعد قليل.",
    noMatchingResources: "لا توجد موارد مطابقة",
    broadenSearch: "جرّب بحثاً أوسع أو امسح أحد عوامل التصفية.",
    clearFilters: "مسح عوامل التصفية",
    uncategorized: "غير مصنف",
    featured: "مميز",
    noDescriptionAdded: "لم تتم إضافة وصف بعد.",
    previous: "السابق",
    next: "التالي",
    page: "صفحة",
    relationshipDiscovery: "اكتشاف قائم على العلاقات",
    connectionMatters: "اعثر على العلاقة الأهم.",
    searchIntro: "ابحث باسم الأداة أو الحاجة أو العلاقة. يفسر نورث ستار سياق البدائل والتكاملات والمنافسين والموارد المشابهة.",
    searchExample: "جرّب «بدائل Jira» أو «تكاملات Slack»",
    alternatives: "البدائل",
    integrations: "التكاملات",
    competitors: "المنافسون",
    ecosystem: "النظام البيئي",
    similarTools: "أدوات مشابهة",
    searchResults: "نتائج البحث",
    resultsFor: "نتائج البحث عن",
    results: "النتائج",
    suggestions: "الاقتراحات",
    allCategories: "كل الفئات",
    pricing: "التسعير",
    clear: "مسح",
    trendingGraph: "الرائج في الرسم البياني",
    liveSignal: "ابدأ بإشارة حية من مورد.",
    liveTrendsEmpty: "ستظهر إشارات الاتجاهات الحية هنا مع نمو الرسم البياني.",
    exploreRelationship: "استكشف علاقة",
    relationshipIntentHelp: "استخدم لغة بسيطة؛ يتعرف نورث ستار على نوايا الرسم البياني الشائعة.",
    openGraphQuery: "فتح استعلام الرسم البياني",
    noResourcesMatched: "لا توجد موارد مطابقة",
    searchNoResults: "جرّب مصطلحاً أوسع أو امسح عاملاً من عوامل التصفية أو استعرض الدليل.",
    resourceNode: "عقدة مورد",
    resourceGraphDescription: "استكشف هذا المورد وعلاقاته الموثقة في الرسم البياني.",
    knowledgeGraphNode: "عقدة رسم المعرفة",
    openNode: "فتح العقدة",
    keepTyping: "تابع الكتابة لإظهار اقتراحات الموارد والعلاقات.",
    resourceSuggestions: "اقتراحات الموارد",
    relatedQueries: "استعلامات ذات صلة",
    relationshipVoteSaved: "تم حفظ تصويت العلاقة",
    relationshipVoteError: "تعذر حفظ تصويتك للعلاقة. يرجى المحاولة مرة أخرى.",
    connectedResource: "استكشف هذا المورد المتصل.",
    strength: "القوة",
    verifiedRelationship: "علاقة موثقة",
    connectionUseful: "هل هذه العلاقة مفيدة؟",
    upvote: "تصويت إيجابي",
    downvote: "تصويت سلبي",
    resourceNotFound: "لم يتم العثور على المورد",
    resourceUnavailable: "قد يكون هذا المورد قد أزيل أو لا يزال بانتظار الموافقة.",
    backToBrowse: "العودة إلى الاستكشاف",
    saved: "محفوظ",
    save: "حفظ",
    openGraph: "فتح الرسم البياني",
    copied: "تم النسخ",
    copyLink: "نسخ الرابط",
    share: "مشاركة",
    visitResource: "زيارة المورد",
    voteSaved: "تم حفظ تصويتك",
    voteError: "تعذر حفظ تصويتك. يرجى المحاولة مرة أخرى.",
    resourceSaved: "تم حفظ المورد",
    resourceRemoved: "تمت إزالة المورد من العناصر المحفوظة",
    savedItemsError: "تعذر تحديث العناصر المحفوظة. يرجى المحاولة مرة أخرى.",
    chooseCollectionFirst: "اختر مجموعة أولاً",
    resourceAddedToCollection: "تمت إضافة المورد إلى المجموعة",
    addToCollectionError: "تعذر إضافة هذا المورد إلى المجموعة.",
    copyLinkError: "تعذر نسخ الرابط",
    nativeShareUnavailable: "المشاركة الأصلية غير متاحة؛ تم نسخ الرابط بدلاً من ذلك.",
    shareDialogError: "تعذر فتح مربع حوار المشاركة",
    connections: "روابط",
    relationshipTypes: "أنواع العلاقات",
    communitySignal: "إشارة المجتمع",
    upvotes: "تصويتات إيجابية",
    knowledgeGraph: "رسم المعرفة",
    exploreConnected: "استكشف الموارد المتصلة",
    noVerifiedConnections: "لا توجد روابط موثقة بعد",
    relationshipAfterModeration: "ستظهر علاقات المجتمع هنا بعد الإشراف.",
    communityFeedback: "ملاحظات المجتمع",
    feedbackGuidance: "صوّت على مدى فائدة هذا المورد للمجتمع.",
    signInToVote: "سجّل الدخول للتصويت أو حفظ هذا المورد.",
    organizeResource: "نظّم هذا المورد",
    organizeGuidance: "أضف هذه العقدة إلى مجموعة منسقة لتتمكن من العودة إليها مع أدوات مرتبطة.",
    chooseCollection: "اختر مجموعة",
    adding: "جارٍ الإضافة…",
    addToCollection: "أضف إلى المجموعة",
    createOne: "أنشئ واحدة",
    organizeSignIn: "سجّل الدخول لتنظيم الموارد في مجموعات.",
    resourceDetails: "تفاصيل المورد",
    views: "المشاهدات",
    notSpecified: "غير محدد",
    unknown: "غير معروف",
    trustContext: "سياق الثقة",
    evidenceSources: "أدلة معتمدة",
    publicHistory: "السجل العام",
    freshness: "الحداثة",
    lastChecked: "آخر تحقق",
    noApprovedEvidence: "لم تتم إضافة أدلة معتمدة بعد.",
    noPublicHistory: "لا يوجد سجل تغييرات عام بعد.",
    current: "حالي",
    needsReview: "يحتاج إلى مراجعة",
    stale: "قديم",
    submitSource: "أضف دليلاً",
    submitSourceIntro: "شارك مصدراً عاماً يساعد المجتمع على التحقق من هذا المورد. يراجع المشرف كل إضافة قبل عرضها علناً.",
    sourceType: "نوع المصدر",
    sourceUrl: "رابط المصدر",
    sourceAttribution: "نسبة المصدر",
    sourceLicenseNote: "ملاحظة الترخيص أو إعادة الاستخدام",
    sourceSubmitted: "تم إرسال الدليل لمراجعة المشرف.",
    sourceSubmitError: "تعذر إرسال هذا الدليل. تحقق من الرابط وحاول مجدداً.",
    sourceTypeOfficial: "الموقع الرسمي",
    sourceTypeDocumentation: "التوثيق",
    sourceTypeRepository: "المستودع",
    sourceTypeCommunity: "مرجع من المجتمع",
    sourceTypeArchive: "أرشيف",
    sourceTypeOther: "مصدر عام آخر",
    pendingSources: "قائمة الأدلة",
    freshnessQueue: "قائمة الحداثة",
    duplicateProposals: "مقترحات التكرار",
    reviewSource: "راجع الدليل",
    approveSource: "اعتمد الدليل",
    rejectSource: "ارفض الدليل",
    supersedeSource: "استبدل الدليل",
    recordFreshness: "سجل الحداثة",
    freshnessNote: "ملاحظة الحداثة",
    proposeAlias: "اقترح اسماً مرجعياً",
    confirmAlias: "أكد الاسم المرجعي",
    aliasConfirmed: "تم تأكيد الاسم المرجعي.",
    aliasNotice: "هذا المورد نسخة مكررة مؤرشفة. تابع إلى المورد المرجعي الموثق.",
    noPendingSources: "لا توجد مصادر أدلة بانتظار المراجعة.",
    noFreshnessItems: "لا توجد موارد معتمدة تحتاج إلى مراجعة الحداثة حالياً.",
    noDuplicateProposals: "لا توجد مقترحات أسماء مرجعية مكررة بانتظار التأكيد.",
    reviewedBy: "أرسله",
    noFreshnessReview: "لم تُسجّل مراجعة للحداثة",
    confirmAliasDetail: "يحفظ التأكيد سجل النسخة المكررة ومراجع المجتمع المرتبطة به؛ ولا يحذف البيانات أو يعيد كتابتها بصمت.",
    switchToDark: "التبديل إلى النسق الداكن",
    switchToLight: "التبديل إلى النسق الفاتح",
    collectionDiscovery: "مجموعات المجتمع",
    collectionDiscoveryIntro: "استكشف مجموعات عامة قابلة لإعادة الاستخدام تحفظ سياق الأدوات وسير العمل.",
    myCollections: "مجموعاتي",
    collectionOwner: "جمعها",
    resourceCount: "موارد",
    noPublicCollections: "لا توجد مجموعات عامة متاحة بعد.",
    signInToCreateCollection: "سجّل الدخول لإنشاء المجموعات وإدارتها.",
    trending: "الرائج",
    trendingIntro: "عرض خفيف لزخم الموارد العامة استناداً إلى إشارات الفائدة الحالية في المنصة.",
    popularNow: "الأكثر شيوعاً الآن",
    trendingEmpty: "لا توجد إشارات شعبية عامة متاحة بعد. استكشف الدليل لبدء بناء السياق.",
    exploreMore: "استكشف موارد إضافية",
    about: "حول",
    aboutIntro: "نورث ستار منصة مفتوحة لذكاء الموارد تساعد على اكتشاف الأدوات ضمن نظامها البيئي الأوسع.",
    aboutMission: "دليل غني بالسياق",
    aboutMissionText: "يتعامل نورث ستار مع كل مورد بوصفه كائناً معرفياً له بيانات وصفية وعلاقات ومصدر وإتاحة لمراجعة المجتمع.",
    aboutPrinciples: "مبادئ المنتج",
    developer: "للمطورين",
    developerIntro: "صُمم نورث ستار ليبقى شفافاً وقابلاً للتوسعة وآمناً لمساهمات المجتمع.",
    apiBoundary: "حدود الواجهة البرمجية الحالية",
    apiBoundaryText: "يستخدم التطبيق الحالي عقوداً داخلية مكتوبة الأنواع. تُخطط واجهة REST عامة ومواصفة OpenAPI بإصدار محدد لكنها غير متاحة بعد.",
    readApiDocs: "اقرأ وثائق حدود الواجهة البرمجية",
    openSourceCollaboration: "تعاون مفتوح المصدر",
    openSourceText: "استكشف المستودع، وساهم عبر عملية الحوكمة الموثقة، ولا تعامل الإثراء الآلي على أنه مصدر للحقيقة.",
    settings: "الإعدادات",
    settingsIntro: "تحكم في تفضيلاتك المحلية في نورث ستار. تبقى هذه الخيارات في هذا المتصفح.",
    appearance: "المظهر",
    language: "اللغة",
    accountSettings: "الحساب",
    openProfile: "افتح الملف الشخصي",
    lightTheme: "النسق الفاتح",
    darkTheme: "النسق الداكن",
    resourceIntelligenceNotLinks: "ذكاء موارد، لا تجميع روابط",
    discoverResourcesContext: "اكتشف الموارد ضمن سياقها.",
    homeHeroDescription: "يربط نورث ستار الأدوات الرقمية بعلاقات موثقة، بحيث يقود كل بحث إلى بدائل وتكاملات وتبعيات والنظام البيئي المحيط.",
    homeSearchPlaceholder: "جرّب «بدائل Jira» أو «تكاملات Figma»",
    homeSearchAria: "ابحث في رسم موارد نورث ستار",
    relationshipShortcuts: "اختصارات مدركة للعلاقات:",
    exploreResources: "استكشف الموارد",
    contributeResource: "أضف مورداً",
    connectedKnowledgeObject: "كائن معرفي متصل",
    verifiedGraph: "رسم موثق",
    designCollaboration: "التصميم والتعاون",
    homeFigmaDescription: "منصة تصميم تعاونية بخريطة علاقات قابلة للاستكشاف.",
    signals: "إشارات",
    builtForGraphNavigation: "مصمم للتنقل عبر الرسم",
    discoveryPaths: "مسارات الاكتشاف",
    homeQuestionTitle: "ابدأ بالسؤال الذي لديك.",
    openRelationshipSearch: "افتح بحث العلاقات",
    findRightTool: "اعثر على الأداة المناسبة",
    findToolDescription: "ابحث بالاسم أو الاستخدام أو الفئة أو العلاقة التي تريد فهمها.",
    searchGraph: "ابحث في الرسم",
    traceConnections: "تتبع الروابط",
    traceConnectionsDescription: "انتقل من مورد إلى بدائله وتكاملاته ومنافسيه ونظامه البيئي.",
    browseNodes: "استعرض العقد",
    buildUsefulStack: "أنشئ مجموعة مفيدة",
    buildStackDescription: "احفظ ونسّق وشارك مجموعات تحافظ على السياق خلف اختياراتك.",
    viewCollections: "اعرض المجموعات",
    graphBenefits: "كيف يساعد الرسم",
    graphBenefitsTitle: "طريقة أهدأ لتقييم مشهد أدوات مزدحم.",
    graphBenefitsDescription: "يحول نورث ستار الدليل إلى طبقة ذكاء. يصمم كل مورد ليحمل بيانات واضحة وسياقاً للعلاقات وإشارات مجتمع وطريقاً إلى نظامه البيئي الأوسع.",
    understandTradeoffs: "افهم المفاضلات",
    tradeoffsDescription: "قارن بدائل موثوقة دون إعادة البحث من البداية.",
    discoverConnections: "اكتشف الروابط",
    connectionsDescription: "أظهر التكاملات والتبعيات التي تؤثر في سير العمل الحقيقي.",
    keepKnowledgeReusable: "حافظ على قابلية إعادة استخدام المعرفة",
    knowledgeReusableDescription: "حوّل النتائج الفردية إلى مجموعات يمكن لفريقك العودة إليها.",
    contributeWithReview: "ساهم مع المراجعة",
    contributeReviewDescription: "أرسل الموارد واقتراحات العلاقات ضمن دورة إشراف بشرية.",
    makeGraphStronger: "اجعل الرسم أقوى",
    graphStrongerTitle: "هل لديك مورد أو علاقة تستحق الرسم؟",
    graphStrongerDescription: "يراجع الأشخاص المساهمات قبل أن تصبح معرفة عامة. ابدأ بمورد ثم أضف السياق الذي يجعله مفيداً.",
    submitAResource: "أرسل مورداً",
    graphExplorerKicker: "رسم المعرفة",
    graphExplorerTitle: "استكشف نظاماً بيئياً لمورد",
    graphExplorerDescription: "اختر مورداً لفحص جواره بعلاقات موثقة من خطوة واحدة. تظل كل علاقة متاحة في قائمة قابلة للوصول أسفل الخريطة المرئية.",
    graphFindResource: "اعثر على مورد لاستكشافه",
    graphSearchPlaceholder: "ابحث عن مورد، مثل Figma أو GitHub",
    graphMatchHeading: "الموارد المطابقة",
    graphResourceFallbackDescription: "استكشف رسم المعرفة لهذا المورد.",
    graphNoMatch: "لا توجد موارد معتمدة تطابق هذا البحث.",
    graphUnavailable: "رسم المورد غير متاح",
    graphUnavailableDescription: "قد يكون المورد غير متاح أو بانتظار الاعتماد.",
    graphChooseOther: "اختر مورداً آخر",
    graphBackToNode: "العودة إلى عرض العقدة",
    graphExploreOther: "استكشف عقدة أخرى",
    graphOneHop: "مستكشف الرسم من خطوة واحدة",
    graphEcosystemSuffix: "النظام البيئي",
    graphBoundedDescription: "يعرض ما يصل إلى 40 ضلع علاقة معتمد و12 عقدة مورد مجاورة. يُحد هذا العرض عمداً للوضوح والأداء.",
    graphRelationshipMap: "خريطة العلاقات",
    graphFocusNode: "عقدة التركيز",
    graphAccessibleList: "قائمة علاقات قابلة للوصول",
    graphAccessibleListDescription: "استخدم هذه القائمة الدلالية لفحص كل ضلع مرئي واتجاهه وحالة التحقق وسياق الدليل.",
    graphOutgoingConnection: "اتصال صادر من",
    graphIncomingConnection: "اتصال وارد إلى",
    graphStrength: "القوة",
    graphVerified: "موثق",
    graphPendingVerification: "بانتظار التحقق",
    graphEvidence: "دليل",
    graphNoEdges: "لا توجد أضلاع معتمدة بعد",
    graphNoEdgesDescription: "تظهر اتصالات المجتمع المقترحة هنا بعد الإشراف البشري.",
    apiKeys: "مفاتيح الواجهة البرمجية",
    apiKeyIntro: "أنشئ مفتاح قراءة فقط لتكامل محدد. احتفظ به سرياً: يعرض نورث ستار المفتاح كاملاً مرة واحدة فقط.",
    createApiKey: "أنشئ مفتاحاً",
    apiKeyName: "اسم المفتاح",
    apiKeyNamePlaceholder: "مثال: عميل البحث الداخلي",
    apiScopes: "نطاقات القراءة",
    dailyQuota: "حصة الطلبات اليومية",
    apiKeySecretWarning: "انسخ هذا المفتاح الآن. لا يمكن عرضه مجدداً بعد إغلاق هذا التنبيه.",
    copyKey: "انسخ المفتاح",
    copiedKey: "تم نسخ المفتاح",
    revokeKey: "ألغ المفتاح",
    revoked: "ملغى",
    active: "نشط",
    noApiKeys: "لم تُنشأ مفاتيح واجهة برمجية بعد.",
    apiUsageToday: "الاستخدام اليوم",
    remainingRequests: "طلبات متبقية",
    noExpiry: "دون انتهاء",
    signInToManageApi: "سجّل الدخول لإنشاء مفاتيح الواجهة البرمجية وإدارتها.",
    searchQuality: "جودة البحث",
    searchQualityIntro: "إشارات إجمالية آمنة للخصوصية وحالات صلة يراجعها البشر. لا تحتفظ القياسات بمعرفات المستخدم أو الجلسة أو عنوان IP.",
    searchVolume: "عمليات البحث",
    zeroResultRate: "معدل عدم وجود نتائج",
    clickThroughRate: "معدل النقر",
    reformulationRate: "معدل إعادة الصياغة",
    averageLatency: "متوسط زمن الاستجابة",
    relevanceCases: "حالات الصلة",
    createEvaluationCase: "أنشئ حالة صلة",
    expectedResourceIds: "معرفات الموارد المتوقعة",
    expectedResourceIdsHelp: "استخدم معرفات الموارد المفصولة بفواصل التي حكم مراجع بشري بصلتها.",
    caseNotes: "ملاحظات المراجعة",
    draft: "مسودة",
    noRelevanceCases: "لا توجد حالات صلة مؤلفة بشرياً حتى الآن.",
    qualityAccessDenied: "جودة البحث متاحة للمشرفين والمديرين.",
    importResources: "استورد الموارد من ملف أو تصدير دردشة",
    importResourcesIntro: "أسقط تصدير واتساب أو ملفاً نصياً أو PDF أو مستند Office أو جدولاً أو عرضاً تقديمياً أو صورة. يستخرج نورث ستار الروابط في الذاكرة فقط.",
    importPrivacy: "يتم التخلص من البيانات الشخصية ورسائل الدردشة وبيانات المرسِل والطوابع الزمنية والملف المصدر. يمكن فقط لروابط الموارد الآمنة الانتقال إلى المراجعة.",
    chooseFile: "اختر ملفاً",
    dropFile: "أسقط ملفاً مدعوماً هنا",
    processingImport: "جارٍ استخراج روابط الموارد…",
    importResults: "نتائج الاستيراد",
    foundCandidates: "مرشح موارد آمن تم العثور عليه",
    rejectedLinks: "رابط غير آمن أو غير صالح تم استبعاده",
    useCandidate: "استخدم هذا المورد",
    imageOcrLocal: "يتم OCR للصور محلياً قبل إرسال أي رابط مكتشف إلى المراجعة.",
    personalDataDiscarded: "لم يتم الاحتفاظ بأي بيانات شخصية.",
  },
} as const;

type CopyKey = keyof typeof copy.en;
type LanguageContextValue = {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  toggleLocale: () => void;
  t: (key: CopyKey) => string;
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function getInitialLocale(getItem: (key: string) => string | null): Locale {
  return getItem("northstar-locale") === "ar" ? "ar" : "en";
}

export function syncLocale(
  locale: Locale,
  documentLike: { documentElement: { lang: string; dir: string } },
  setItem: (key: string, value: string) => void
) {
  documentLike.documentElement.lang = locale;
  documentLike.documentElement.dir = locale === "ar" ? "rtl" : "ltr";
  setItem("northstar-locale", locale);
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [locale, setLocale] = useState<Locale>(() =>
    typeof window !== "undefined" ? getInitialLocale((key) => window.localStorage.getItem(key)) : "en"
  );

  useEffect(() => {
    syncLocale(locale, document, (key, value) => window.localStorage.setItem(key, value));
  }, [locale]);

  const value = useMemo(
    () => ({
      locale,
      setLocale,
      toggleLocale: () => setLocale((current) => (current === "en" ? "ar" : "en")),
      t: (key: CopyKey) => copy[locale][key],
    }),
    [locale]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const value = useContext(LanguageContext);
  if (!value) throw new Error("useLanguage must be used within LanguageProvider");
  return value;
}
